---
# -*- coding: utf-8 -*-

language: python
sudo: required
cache: pip
python:
  - "2.7"
services:
  - docker

install:
  - pip install --upgrade ansible ansible-lint ansible-test yamllint

before_script:
  - ansible --version
  - ansible-lint --version
  - yamllint --version
  - ERRORS=0

script:
  - for dir in *; do
      if [ -d "$dir" ]; then
        echo "$dir";
        ansible-lint -R -r .testenv/lint-rules/ "$dir" || let ERRORS+=1 ;
      fi ;
    done
  - for dir in *; do
      if [ -d "$dir" ]; then
        echo "$dir";
        yamllint -c .testenv/yamllint.yml "$dir" || let ERRORS+=1 ;
      fi ;
    done
  - if [ $ERRORS -ne 0 ]; then exit $ERRORS; fi
  - for dir in *; do
      if [ -d "$dir" ]; then
        echo "$dir";
        ansible-test --image debian:9 "$dir" || let ERRORS+=1 ;
        ansible-test --image debian:8 "$dir" || let ERRORS+=1 ;
        ansible-test --image debian:7 "$dir" || let ERRORS+=1 ;
        ansible-test --image ubuntu:16 "$dir" || let ERRORS+=1 ;
        ansible-test --image ubuntu:14 "$dir" || let ERRORS+=1 ;
        ansible-test --image centos:7 "$dir" || let ERRORS+=1 ;
        ansible-test --image centos:6 "$dir" || let ERRORS+=1 ;
      fi ;
    done
  - exit $ERRORS

# vim: set ts=2 sw=2 tw=2 :
