---

- name: create logrotate configuration directory
  file:
    path: '{{ logrotate_cfg_d }}'
    state: directory
    owner: root
    group: root
    mode: 0755
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0

- name: create main logrotate configuration
  template:
    src: etc/logrotate.conf.j2
    dest: '{{ logrotate_cfg }}'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0

- name: create logrotate configurations
  template:
    src: 'etc/logrotate.d/{{ item.type }}.j2'
    dest: '{{ logrotate_cfg_d }}/{{ item.name }}.conf'
    owner: root
    group: root
    mode: 0644
    seuser: system_u
    serole: object_r
    setype: etc_t
    selevel: s0
  with_items: '{{ logrotate_custom_cfg }}'
  when: item.name is defined and item.name and
        item.type is defined and item.type
