---

- name: clean old jitsi-meet configuration
  file:
    path: '{{ jitsi_meet_old_nginx_config }}'
    state: absent

- name: create vhost
  template:
    src: 'etc/nginx/conf.d/jitsi_meet.conf.j2'
    dest: '{{ nginx_vhosts_dir }}/{{ item }}.conf'
    owner: root
    group: root
    mode: 0644
  with_items: '{{ jitsi_meet_domains }}'
  notify:
    - 'nginx_check_config'
