---

- name: install jitsi-meet related packages
  package:
    name: '{{ item }}'
    state: present
    update_cache: yes
  tags:
    - 'role::jitsi_meet'
    - 'role::jitsi_meet:install'
#  when: ansible_os_family == 'Debian'
  with_items: '{{ jitsi_meet_related_packages }}'

- name: get jitsi repository key
  apt_key:
    url: '{{ jitsi_meet_apt_key }}'
    state: present
  tags:
    - 'role::jitsi_meet'
    - 'role::jitsi_meet:install'
  when: ansible_os_family == 'Debian'

- name: add jitsi repository
  apt_repository:
    repo: '{{ jitsi_meet_apt_repository }}'
    state: present
  tags:
    - 'role::jitsi_meet'
    - 'role::jitsi_meet:install'
  when: ansible_os_family == 'Debian'
  notify:
    - 'jitsi_meet_update_repo_cache'

- name: install jitsi meet
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ jitsi_meet_packages }}'
  tags:
    - 'role::jitsi_meet'
    - 'role::jitsi_meet:install'
  when: ansible_os_family == 'Debian'